<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <AppxPackage>false</AppxPackage>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
    <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>
    <ShouldImportMsixDesignTimeTargets>false</ShouldImportMsixDesignTimeTargets>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <AssemblyName>KeyboardDebounce</AssemblyName>
    <RootNamespace>KeyboardDebounce</RootNamespace>
    <Version>0.2.0</Version>
    <ApplicationIcon>assets\keyboard-debounce.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\**\*.cs" />
    <Content Remove="Assets\**\*" />
    <EmbeddedResource Include="LICENSE" LogicalName="KeyboardDebounce.LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="src\App.xaml" />
    <Page Remove="dist\**\*.xaml" />
    <ApplicationDefinition Remove="dist\**\*.xaml" />
    <Content Remove="dist\**\*" />
    <EmbeddedResource Remove="dist\**\*" />
    <ApplicationDefinition Include="src\App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup Condition="'$(EnableMsixTooling)' == 'true'">
    <Page Remove="$(NuGetPackageRoot)microsoft.windows.sdk.buildtools.msix\**\*.xaml" />
    <Page Remove="$(PkgMicrosoft_Windows_SDK_BuildTools_MSIX)\build\**\*.xaml" />
    <Page Remove="dist\nuget-packages\microsoft.windows.sdk.buildtools.msix\**\*.xaml" />
    <Page Remove="$(NuGetPackageRoot)microsoft.windowsappsdk.winui\**\generic.xaml" />
    <Page Remove="dist\nuget-packages\microsoft.windowsappsdk.winui\**\generic.xaml" />
    <PropertyPageSchema Remove="$(PkgMicrosoft_Windows_SDK_BuildTools_MSIX)\build\ProjectItemsSchema.xaml" />
    <PropertyPageSchema Remove="$(PkgMicrosoft_Windows_SDK_BuildTools_MSIX)\build\Rules\*.xaml" />
  </ItemGroup>
</Project>
